// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DecryptFile(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function EncryptFile(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetConfig():Promise<backend.Config>;

export function GetKeyLabelsForSlot(arg1:number,arg2:string):Promise<Array<string>>;

export function GetSlots():Promise<Record<number, string>>;

export function SaveConfig(arg1:backend.Config):Promise<string>;

export function SelectFileToShowDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectModuleFile():Promise<string>;

export function SelectSaveFileToShowDialog(arg1:string,arg2:string):Promise<string>;

export function UnsealVault(arg1:string):Promise<void>;
