// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2, arg3, arg4);
}

export function EncryptFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2, arg3, arg4, arg5);
}

export function GetKeyLabelsForSlot(arg1, arg2) {
  return window['go']['main']['App']['GetKeyLabelsForSlot'](arg1, arg2);
}

export function GetSlots() {
  return window['go']['main']['App']['GetSlots']();
}

export function SelectFileToShowDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFileToShowDialog'](arg1, arg2, arg3);
}

export function SelectSaveFileToShowDialog(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFileToShowDialog'](arg1, arg2);
}
